---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: pcf-prometheus-pipeline

params:
  opsman_url:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  uaa_bosh_exporter_client_secret:
  uaa_clients_firehose_exporter_secret:
  uaa_clients_cf_exporter_secret:
  pcf_opsman_admin_uaa_client: 
  pcf_opsman_admin_uaa_secret: 
  pcf_opsman_admin_uaa_system_domain: 
  pcf_opsman_bosh_director_ip: 
  pcf_opsman_bosh_director_password: 
  pcf_opsman_uaa_admin_password: 

run:
  path: pcf-prometheus-pipeline/pipeline/tasks/create-uaa-clients.sh
